# 
# 记录我成功部署模型到windows系统所用的DockerFile
#

ARG PYTORCH="1.9.0"
ARG CUDA="10.2"
ARG CUDNN="7"
FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ARG MMCV="1.3.17"
ARG MMCLS="0.19.0"
ARG MMDET="2.20.0"

ENV PYTHONUNBUFFERED TRUE

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    ca-certificates \
    g++ \
    openjdk-11-jre-headless \
    git \
    openssh-server \
    # MMCls Requirements
    libgl1-mesa-glx


ENV PATH="/opt/conda/bin:$PATH"
RUN export FORCE_CUDA=1

# TORCHSEVER
RUN pip install torchserve torch-model-archiver -i https://pypi.tuna.tsinghua.edu.cn/simple

# MMLAB
ARG PYTORCH
ARG CUDA


RUN pip install opencv-python==4.5.5.62 -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN ["/bin/bash", "-c", "pip install mmcv-full==${MMCV} -f https://download.openmmlab.com/mmcv/dist/cu${CUDA//./}/torch${PYTORCH}/index.html"]

RUN pip install mmcls==${MMCLS} -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install mmdet==${MMDET} -i https://pypi.tuna.tsinghua.edu.cn/simple

RUN useradd -m model-server \
    && mkdir -p /home/model-server/tmp

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN chmod +x /usr/local/bin/entrypoint.sh \
    && chown -R model-server /home/model-server

COPY config.properties /home/model-server/config.properties
RUN mkdir /home/model-server/model-store && chown -R model-server /home/model-server/model-store

EXPOSE 8080 8081 8082

USER model-server
WORKDIR /home/model-server
ENV TEMP=/home/model-server/tmp
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["serve"]
